/run/printProgress 1
/run/reinitializeGeometry

/g4cmp/verbose 2
/g4cmp/chargeBounces 1000

/g4cmp/qAbsProbGeSi 0
/g4cmp/qReflProbGeSi 0.5
/g4cmp/qAbsProbSiGe 0
/g4cmp/qReflProbSiGe 0.5


/run/initialize
#
# Create a scene handler for a specific graphics system
# (Edit the next line(s) to choose another graphic system)
#
/vis/open OGLI
/vis/viewer/set/upVector 0 0 1
/vis/viewer/set/viewpointVector 0 1 0
/vis/viewer/panTo 0 0 100 nm
/vis/viewer/zoom 7000
/vis/drawVolume
#
# for drawing the tracks
# (if too many tracks cause core dump => storeTrajectory 0)
/tracking/storeTrajectory 1
/vis/scene/endOfEventAction accumulate
/vis/scene/add/trajectories
/vis/scene/add/hits
#
# Make phonon polarization modes distinguishable
# Add colors for e-/h+
/vis/modeling/trajectories/create/drawByParticleID
/vis/modeling/trajectories/drawByParticleID-0/set phononTS Red 
/vis/modeling/trajectories/drawByParticleID-0/set phononTF Green
/vis/modeling/trajectories/drawByParticleID-0/set phononL Blue
/vis/modeling/trajectories/drawByParticleID-0/set G4CMPDriftElectron Yellow
/vis/modeling/trajectories/drawByParticleID-0/set G4CMPDriftHole Orange
#/vis/modeling/trajectories/drawByParticleID-0/set G4CMPDriftHole White
#
# Filter for only charge
/vis/filtering/trajectories/create/particleFilter
/vis/filtering/trajectories/particleFilter-0/add G4CMPDriftElectron
/vis/filtering/trajectories/particleFilter-0/add G4CMPDriftHole
#/vis/filtering/trajectories/particleFilter-0/add phononL
#/vis/filtering/trajectories/particleFilter-0/add phononTS
#/vis/filtering/trajectories/particleFilter-0/add phononTF
#/vis/filtering/trajectories/particleFilter-0/invert true
#

# Generate an e-/h+ pair per event for 10 events 
/gun/number 1
/run/beamOn 10
#
# Write event display to output files for analysis (face and side views)
#/vis/ogl/set/printFilename g4cmpHeterostructure.eps
#/vis/ogl/set/printMode pixmap
#/vis/ogl/export


